name: notifications_implementation
description: An implementation of 'notifications_interface' which helps in
  working with notifications a loosely coupled manner.
version: 0.0.1
author: Pavel Sulimau
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  notifications_interface:
    path: '../notifications_interface/'
  overlay_support: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
