name: notifications_implementation
description: An implementation of 'notifications_interface' which helps in
  working with notifications a loosely coupled manner.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  notifications_interface:
    git:
      url: https://github.com/Pavel-Sulimau/light_notifications.git
      path: notifications_interface
    # path: '../notifications_interface/'
  overlay_support: ^1.2.1

dev_dependencies:
  stanalysis:
    git: https://github.com/Pavel-Sulimau/stanalysis.git
